#!/bin/sh
#PJM -L "node=1"
#PJM -L "rscgrp=small-s3"
#PJM -L "elapse=24:00:00"
#PJM --mpi max-proc-per-node=4
#PJM --llio cn-cache-size=6Gi # default = 128Mb
#PJM --llio sio-read-cache=on
#PJM -x PJM_LLIO_GFSCACHE=/vol0003:/vol0004:/vol0005
#PJM -g hp240116
#PJM -s

#  PJM -L "elapse=24:00:00"
# other PJM flags
#  --llio localtmp-size=500Mi

# do not create empty stdout/stderr files
export PLE_MPI_STD_EMPTYFILE=off
export OMP_NUM_THREADS=12

# script to merge DALES output
# for Fugaku compute nodes
# for cloud botany 2021


. /vol0500/data/hp240116/spack/share/spack/setup-env.sh
spack load cdo%fj

CDO=cdo

# requires cdo version >= 2.0.4 to handle grid right
# and preserve xt,yt

# find number of tiles in X and Y directions.
NX=`ls 000/cape.x*y000.001.nc | wc -l`
NY=`ls [0-9]* -d | wc -l`


# control CPU binding, so that we can run several cdo processes
# in parallel and have them on different CPU cores
# this is from 2021, things may have changed
# at that time, effort was needed to not have all cdo
# bound to the same CPU core.

# numactl seems not effective on OpenMP programs
# otherwise numactl --cpunodebind=4
# 4,5,6,7 are the core groups to use
# node 4 cpus: 12 13 14 15 16 17 18 19 20 21 22 23
# node 5 cpus: 24 25 26 27 28 29 30 31 32 33 34 35
# node 6 cpus: 36 37 38 39 40 41 42 43 44 45 46 47
# node 7 cpus: 48 49 50 51 52 53 54 55 56 57 58 59
#

#export GOMP_CPU_AFFINITY="12,13,14,15,16,17,18,19"

#export GOMP_CPU_AFFINITY="24,25,26,27,28,29,30,31"
#echo -n "start merging cape "
#date

echo "NX: $NX  NY: $NY"

# === FIELDDUMP ===

echo -n "start merging fielddump "
date
n=0
for y in `seq -f "%03.0f" 0 $((NY - 1))` ; do
    echo -n "    start merging fielddump row $y "
    date
    export GOMP_CPU_AFFINITY=$((12*(n+1)))
    $CDO -f nc4 -r -O collgrid,$NX,u,v,w,thl,qt,ql $y/fielddump.*.nc  tmp-fielddump.$y.nc &
    #    # add sv001 here, if present?
    n=$((n+1))
    if [ $n -eq 4 ] ; then
	wait
	n=0
    fi
done

echo -n "    start final merges fielddump"

export GOMP_CPU_AFFINITY=24
$CDO -f nc4 -z zip_6 -r -O collgrid,1,ql    tmp-fielddump.*.nc fielddump-ql.nc &
export GOMP_CPU_AFFINITY=36
$CDO -f nc4 -z zip_6 -r -O collgrid,1,qt    tmp-fielddump.*.nc fielddump-qt.nc &
export GOMP_CPU_AFFINITY=48
$CDO -f nc4 -z zip_6 -r -O collgrid,1,thl  tmp-fielddump.*.nc fielddump-thl.nc &
export GOMP_CPU_AFFINITY=16
$CDO -f nc4 -z zip_6 -r -O collgrid,1,w   tmp-fielddump.*.nc fielddump-w.nc &
export GOMP_CPU_AFFINITY=30
$CDO -f nc4 -z zip_6 -r -O collgrid,1,v   tmp-fielddump.*.nc fielddump-v.nc &
export GOMP_CPU_AFFINITY=40
$CDO -f nc4 -z zip_6 -r -O collgrid,1,u   tmp-fielddump.*.nc fielddump-u.nc &
wait

echo "cleaning up"
rm tmp-*.nc
