#!/bin/bash
#SBATCH --ntasks=32
#SBATCH --cpus-per-task=1
#SBATCH --partition=rome
#SBATCH --time=72:00:00

module load 2024
module load CDO/2.4.4-gompi-2024a
CDO=cdo

# === CROSS ===
# find number of tiles in X and Y directions.
NX=`ls 000/cape.x*y000.001.nc | wc -l`
NY=`ls [0-9]* -d | wc -l`

$CDO -f nc4 -r -O collgrid 023/crossxz.0768.x*.001.nc  crossxz.nc
wait

# === CAPE ===

# merge rows
n=0
for y in `seq -f "%03.0f" 0 $((NY - 1))` ; do
    echo -n "    start merging cape row $y "
    date
    $CDO -f nc4 -r -O collgrid $y/cape.x*y$y.001.nc  tmp-cape.$y.nc &
done
wait

echo -n "    start final cape merge "
#final merge
$CDO -f nc4 -z zip_6 -r -O collgrid,1,lwp tmp-cape.*.nc cape-lwp.nc  &
$CDO -f nc4 -z zip_6 -r -O collgrid,1,rwp tmp-cape.*.nc cape-rwp.nc  &
$CDO -f nc4 -z zip_6 -r -O collgrid,1,twp tmp-cape.*.nc cape-twp.nc  &
$CDO -f nc4 -z zip_6 -r -O collgrid,1,cldtop tmp-cape.*.nc cape-cldtop.nc &
$CDO -f nc4 -z zip_6 -r -O collgrid,1,surfprec tmp-cape.*.nc cape-surfprec.nc &
$CDO -f nc4 -z zip_6 -r -O collgrid,1,thlcb tmp-cape.*.nc cape-thlcb.nc &
$CDO -f nc4 -z zip_6 -r -O collgrid,1,wcb tmp-cape.*.nc cape-wcb.nc &

wait
rm tmp-cape*
